### ISSUE TITLE
В методе проверки пароль второй, а не первый!

### ISSUE THREAD

**Issue by highfeed** [SeNaP/node-robokassa#5]
Я мучался столько времени. 

Парень, не стоит выкладывать такие модули.. Одни проблемы.

**Comment by SeNaP** [comment]
Создай форк

**Comment by highfeed** [comment]
Уже все, я сделал свой модуль.  Нужно делать нормальные модули.  Там ещё
критическая ошибка в проверке.
23 Май 2015 г. 5:43 пользователь "SeNaP" notifications@github.com написал:
